### ISSUE TITLE
Ruby: minor improvements

### ISSUE THREAD

**Issue by masatake** [universal-ctags/ctags#2480]
Eventually, we may have to rewrite ruby parser with a completely token oriented way to do more interesting things like stacking subparser for Ruby on Rails.

HOWEVER, there are some areas we can improve the current line-oriented parser.

Easy ones:
- [x] capture accessors defined with attr_accessor
      "attrMethod" language speific extra can be added.
      See #408.
- [ ] introduce script kind for capturing 'require "foo"'.
- [x] capture CONSTANT (is it possible in the current implementation?)
- [x] handle mixin (#2476).
- [ ] ~capture "class << HTTP" with an anonymous tag.~
- [x] end field for classes, modules, and method.
- [ ] alias_method ( #408, #2495)
- [ ] alias ( #408, #2495 )
      ripper-tags defines kind for alias/a.
- [ ] capture autoloaded module as reference tags

Hard ones:
- [ ] signature field for methods (is it possible in the current implementation?)
- [ ] ignore here-doc area ( #454 )

Unknown:
- [ ] capture Class.new with anonymous tag (#2408 )
- [ ] subparser for rails ( #408 )

NOTE:
* Please, read ctags(1) and understand the fundamental concepts in ctags including the definition tags, reference tags, kinds, fields, extras, and pseudo-tags before adding something.
* if possible, I would you to read parsers/ruby.c before adding something.
* @masatake will update, delete or edit your comments for keeping this as our TODO list.

**Comment by colinlieberman** [comment]
Just wanted to +1 this - the issue with signatures including string literals is particularly problematic with rubocop eg having to change

```
class MyClass # rubocop:disable Metrics/ClassLength
...
```

to 

```
# rubocop:disable Metrics/ClassLength
class MyClass
  ...
end
# rubocop:enable Metrics/ClassLength
```

and yes, obviously there's another solution for this, but for utility classes that are eg for looking up a number of items from a large dataset, that's the reason the disable options exist

**Comment by masatake** [comment]
@colinlieberman, please open a new issue for the topic.
I would like you to show an example input. I expect the input is not so large.
Please, remember that I don't know ruby well.

**Comment by colinlieberman** [comment]
> @colinlieberman, please open a new issue for the topic.
> I would like you to show an example input. I expect the input is not so large.
> Please, remember that I don't know ruby well.

Thanks, @masatake - i'm trying to put together a good example for you, but not being able to duplicate the issue. 

I noticed this with an atom plugin, and I'm friends with its author, so I'm poking at this a bit with them. I'll update this to either strike my original comment or create a new issue as you suggest depending on what we find

**Comment by masatake** [comment]
@colinlieberman, see  #2630 and write example inputs if you have.
#2630 may fix "the parsing bug with signatures including comments".
With the change, ctags can extract the signature for `cat` properly from input:
```
class X
  def cat (n = ")",              # comment
           m = "misssing")
    return n + m
  end
end
```

**Comment by colinlieberman** [comment]
Hi, @masatake I'll check that out thanks.

I didn't see your comment before I made #2632 

I'll have a look at #2630 and close mine if it's a dup

**Comment by masatake** [comment]
You don't have to close #2632. You reported yet another bug.
I will merge #2630. It is nothing to do with #2632.
