### ISSUE TITLE
Various crashes

### ISSUE THREAD

**Issue by masatake** [universal-ctags/ctags#4090]
```
ctags: ./main/vstring.h:111: parsing adcli/master--lcopy/archives/build/Makefile.am:8 as Make
    (core dumped) ${CTAGS}\
         -R --kinds-all='*' --fields='*' --fields-all='*' --extras='*' --extras-all='*' --roles-all.'*'='*'  \
         --options-maybe=$(encode_optlib_dir "$d") -o $(encode_tag_file "$d") "$d"
--
ctags: ./main/vstring.h:111: parsing alsa-tools/master--lcopy/archives/ld10k1/include/Makefile.am:33 as Make
    (core dumped) ${CTAGS}\
         -R --kinds-all='*' --fields='*' --fields-all='*' --extras='*' --extras-all='*' --roles-all.'*'='*'  \
         --options-maybe=$(encode_optlib_dir "$d") -o $(encode_tag_file "$d") "$d"
--
ctags: ./main/vstring.h:111: parsing apache-commons-lang3/master--lcopy/archives/src/test/java/org/apache/commons/lang3/math/NumberUtilsTest.java:1050 as Java
    (core dumped) ${CTAGS}\
         -R --kinds-all='*' --fields='*' --fields-all='*' --extras='*' --extras-all='*' --roles-all.'*'='*'  \
         --options-maybe=$(encode_optlib_dir "$d") -o $(encode_tag_file "$d") "$d"
--
ctags: parsers/cxx/cxx_parser_tokenizer.c:1083: parsing bison/master--lcopy/archives/data/skeletons/lalr1.cc:25 as C++
    (core dumped) ${CTAGS}\
         -R --kinds-all='*' --fields='*' --fields-all='*' --extras='*' --extras-all='*' --roles-all.'*'='*'  \
         --options-maybe=$(encode_optlib_dir "$d") -o $(encode_tag_file "$d") "$d"
--
ctags: ./main/vstring.h:111: parsing gcc/master--lcopy/archives/libphobos/src/std/encoding.d:1953 as D
    (core dumped) ${CTAGS}\
         -R --kinds-all='*' --fields='*' --fields-all='*' --extras='*' --extras-all='*' --roles-all.'*'='*'  \
         --options-maybe=$(encode_optlib_dir "$d") -o $(encode_tag_file "$d") "$d"
--
ctags: parsers/cxx/cxx_parser_tokenizer.c:1083: parsing gimp/master--lcopy/archives/libgimpwidgets/gimppickbutton-quartz.c:178 as C
    (core dumped) ${CTAGS}\
         -R --kinds-all='*' --fields='*' --fields-all='*' --extras='*' --extras-all='*' --roles-all.'*'='*'  \
         --options-maybe=$(encode_optlib_dir "$d") -o $(encode_tag_file "$d") "$d"
--
ctags: ./main/vstring.h:111: parsing gnome-autoar/master--lcopy/archives/tests/files/extract/test-symlink-parent/reference/arextract/foo.jsx:1 as JavaS}\
        ript
    (core dumped) ${CTAGS}\
         -R --kinds-all='*' --fields='*' --fields-all='*' --extras='*' --extras-all='*' --roles-all.'*'='*'  \
         --options-maybe=$(encode_optlib_dir "$d") -o $(encode_tag_file "$d") "$d"
--
ctags: ./main/vstring.h:111: parsing hunspell-uk/master--lcopy/archives/src/main/java/org/dict_uk/common/UkDictComparator.java:24 as Java
    (core dumped) ${CTAGS}\
         -R --kinds-all='*' --fields='*' --fields-all='*' --extras='*' --extras-all='*' --roles-all.'*'='*'  \
         --options-maybe=$(encode_optlib_dir "$d") -o $(encode_tag_file "$d") "$d"
--
ctags: ./main/vstring.h:111: parsing jsoup/master--lcopy/archives/src/test/java/org/jsoup/helper/DataUtilTest.java:82 as Java
    (core dumped) ${CTAGS}\
         -R --kinds-all='*' --fields='*' --fields-all='*' --extras='*' --extras-all='*' --roles-all.'*'='*'  \
         --options-maybe=$(encode_optlib_dir "$d") -o $(encode_tag_file "$d") "$d"
--
ctags: main/read.c:1173: parsing libguestfs/master--lcopy/archives/fish/test-add-domain.sh:102 as Ant
    (core dumped) ${CTAGS}\
         -R --kinds-all='*' --fields='*' --fields-all='*' --extras='*' --extras-all='*' --roles-all.'*'='*'  \
         --options-maybe=$(encode_optlib_dir "$d") -o $(encode_tag_file "$d") "$d"
--
ctags: parsers/cxx/cxx_parser_tokenizer.c:1083: parsing libreoffice/master--lcopy/archives/libreofficekit/qa/tilebench/tilebench.cxx:614 as C++
    (core dumped) ${CTAGS}\
         -R --kinds-all='*' --fields='*' --fields-all='*' --extras='*' --extras-all='*' --roles-all.'*'='*'  \
         --options-maybe=$(encode_optlib_dir "$d") -o $(encode_tag_file "$d") "$d"
--
ctags: parsers/cxx/cxx_parser_tokenizer.c:1083: parsing openssl/master--lcopy/archives/test/json_test.c:309 as C
    (core dumped) ${CTAGS}\
         -R --kinds-all='*' --fields='*' --fields-all='*' --extras='*' --extras-all='*' --roles-all.'*'='*'  \
         --options-maybe=$(encode_optlib_dir "$d") -o $(encode_tag_file "$d") "$d"
--
ctags: ./main/vstring.h:111: parsing rust/master--lcopy/archives/compiler/rustc_parse_format/src/tests.rs:468 as Rust
    (core dumped) ${CTAGS}\
         -R --kinds-all='*' --fields='*' --fields-all='*' --extras='*' --extras-all='*' --roles-all.'*'='*'  \
         --options-maybe=$(encode_optlib_dir "$d") -o $(encode_tag_file "$d") "$d"
--
ctags: ./main/vstring.h:111: parsing stratisd/master--lcopy/archives/src/engine/shared.rs:409 as Rust
    (core dumped) ${CTAGS}\
         -R --kinds-all='*' --fields='*' --fields-all='*' --extras='*' --extras-all='*' --roles-all.'*'='*'  \
         --options-maybe=$(encode_optlib_dir "$d") -o $(encode_tag_file "$d") "$d"
```

- [X] Make and Automake may be fixed in #4088.
- [X] JavaScript may be fixed in #4087.
- [X] C++ one is reported separately in #4089. Closed via #4221.
- [x] Java one is reported separately in #4222.　Closed via #4234.

**Comment by masatake** [comment]
#4089 is closed via #4221.
