### ISSUE TITLE
Tracker for documentation for v1.0

### ISSUE THREAD

**Issue by ffes** [universal-ctags/ctags#674]
This is a **tracking** issue to mark keep track of thing that need to be done to the documentation for the release of 1.0

- [ ] Update the man page #657 
- [ ] Organize the `docs` directory to combine the user docs and hacking docs
- [ ] Add and update `old-doc/EXTENDING.html` to the docs, which is for peeple who writes a parser. Maybe we need to find a good name for that.
- [ ] Update `format.rst`, which is for people who writes a tool reading tags file. Maybe create tags-format.5 from this as well

This is **not** the place to discuss details about **specific issues** mentioned here. Use separate issues for that.

**Comment by cweagans** [comment]
I'd also like to add that the `old-doc` directory should go away, so all the docs that are in there should be merged with our docs.

**Comment by ffes** [comment]
@cweagans you are right. I added it to the list. Thanks

**Comment by ffes** [comment]
I added `INSTALL` to the list above. I think it is still useful and should be incorporated in the docs as well, presumably added to `autotools.rst`. But with #676 going on, I will ask in that PR.

**Comment by masatake** [comment]
Sorry to be late about this.

I would like to split this into two stages: just writing and cleaning up.
Milestone 0.8 is for writing. I will work on this.
Milestone 0.9 is for cleaning up.
